version: '3.8'
services:
  db:
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD: 'nycuml912'
      MYSQL_DATABASE: 'innolux_db'
      MYSQL_USER: 'innolux'
      MYSQL_PASSWORD: 'nycuml912'
    ports:
      - "3306:3306"

  app:
    image: python:3.8
    volumes:
      - ./backend/app:/usr/src/app
    working_dir: /usr/src/app
    command: ./install.sh
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USER: innolux
      DATABASE_PASSWORD: 'nycuml912'
      DATABASE_NAME: innolux_db

volumes:
  db-data:
